Refactoring project structure
pavelk123/cryptocurrency-service pull request #1
Opened 2024-05-06 17:05 UTC by pavelk123

2024-05-08 19:02 UTC, ihippik requested changes

2024-05-08 19:02 UTC, ihippik commented on config/config.go
>  	"github.com/sethvargo/go-envconfig"
не осортированыф импорты
1) стандартная либа
2) сторонние пакеты
3) внутренние пакеты

2024-05-08 19:02 UTC, ihippik commented on config/config.go
> +		return nil, fmt.Errorf("config process err %w", err)
двоеточие нужно ставить, а то не поймешь где оригинальная ошибка начинается

2024-05-08 19:02 UTC, ihippik commented on internal/app/app.go
> +	db, err := InitDBConn(a.cfg.DB)
все инициализации в main файле

2024-05-08 19:02 UTC, ihippik commented on internal/app/app.go
> +	provider := crypto_currency.NewProvider(&http.Client{}, a.cfg.ProviderAPIURL, a.cfg.ProviderAPIKey)
в пакете http есть дефолтный клиент

2024-05-08 19:02 UTC, ihippik commented on internal/app/app.go
> +	"github.com/pavelk123/cryptocurrency-service/internal/crypto-currency"
почитай какие правила именования пакетов

2024-05-08 19:02 UTC, ihippik commented on internal/app/app.go
> +			log.Fatalf("Failed to listen and serve: %v", err)
фатал мы не используем

2024-05-08 19:02 UTC, ihippik commented on internal/app/app.go
> +func InitDBConn(cfgDB *config.DBConfig) (*sqlx.DB, error) {
инициализация в main

2024-05-08 19:02 UTC, ihippik commented on internal/crypto-currency/handler.go
> +	if err == nil {
попробуй без if обойтись

2024-05-08 19:02 UTC, ihippik commented on internal/crypto-currency/provider.go
>  	err = json.Unmarshal(body, &dtos)
короткий вариант проверки ошибок

2024-05-08 19:02 UTC, ihippik commented on internal/crypto-currency/repository.go
>  	err := repo.db.QueryRowxContext(
запрос нужно переписывать - и вообще первый раз вижу человека, который правый джоин использует)

2024-05-08 19:02 UTC, ihippik commented on internal/crypto-currency/repository.go
>  	rows, err := repo.db.QueryxContext(
тоже самое

2024-05-08 19:02 UTC, ihippik commented on internal/crypto-currency/service.go
>  					s.logger.Error("Error updating data:%w", err)
ошибки да и сами текста логов обычно пишутся с маленькой буквы

2024-05-08 19:02 UTC, ihippik commented on config/config.go
> +	DB                    *DBConfig
можно префикс перменной указывать

2024-05-08 19:02 UTC, ihippik commented on internal/crypto-currency/handler.go
> +	case errors.Is(err, errNotFound):
кейсы нужны выстраивать в порядке их вероятности - серху наиболее вероятные

2024-05-08 19:02 UTC, ihippik commented on internal/crypto-currency/repository.go
>  		ctx,
тоже думаю запрос переписать нужно и inner join - это обычный join помоему
тепер что gpt это писал?)

2024-05-12 11:09 UTC, pavelk123 commented on config/config.go
>  	"github.com/sethvargo/go-envconfig"
@ihippik исправлено

2024-05-12 11:11 UTC, pavelk123 commented on config/config.go
> +		return nil, fmt.Errorf("config process err %w", err)
@ihippik исправлено)

2024-05-12 11:11 UTC, pavelk123 commented on internal/app/app.go
> +	db, err := InitDBConn(a.cfg.DB)
@ihippik исправлено)

2024-05-12 11:11 UTC, pavelk123 commented on internal/app/app.go
> +	provider := crypto_currency.NewProvider(&http.Client{}, a.cfg.ProviderAPIURL, a.cfg.ProviderAPIKey)
@ihippik исправлено)

2024-05-12 11:11 UTC, pavelk123 commented on internal/app/app.go
> +	"github.com/pavelk123/cryptocurrency-service/internal/crypto-currency"
@ihippik исправлено

2024-05-12 11:12 UTC, pavelk123 commented on internal/app/app.go
> +			log.Fatalf("Failed to listen and serve: %v", err)
@ihippik заменено на return

2024-05-12 11:12 UTC, pavelk123 commented on internal/app/app.go
> +func InitDBConn(cfgDB *config.DBConfig) (*sqlx.DB, error) {
@ihippik исправлено)

2024-05-12 11:13 UTC, pavelk123 commented on internal/crypto-currency/handler.go
> +	if err == nil {
@ihippik сделал через return

2024-05-12 11:13 UTC, pavelk123 commented on internal/crypto-currency/provider.go
>  	err = json.Unmarshal(body, &dtos)
@ihippik исправлено)

2024-05-12 11:14 UTC, pavelk123 commented on internal/crypto-currency/repository.go
>  	err := repo.db.QueryRowxContext(
@ihippik переписал с использованием WITH ... AS, LEFT JOIN)

2024-05-12 11:15 UTC, pavelk123 commented on internal/crypto-currency/repository.go
>  	rows, err := repo.db.QueryxContext(
@ihippik переписал с использованием WITH ... AS, LEFT JOIN)

2024-05-12 11:15 UTC, pavelk123 commented on internal/crypto-currency/service.go
>  					s.logger.Error("Error updating data:%w", err)
@ihippik исправлено)

2024-05-12 11:16 UTC, pavelk123 commented on config/config.go
> +	DB                    *DBConfig
@ihippik исправлено, действительно удобно)

2024-05-12 11:16 UTC, pavelk123 commented on internal/crypto-currency/handler.go
> +	case errors.Is(err, errNotFound):
@ihippik исправлено

2024-05-12 11:17 UTC, pavelk123 commented on internal/crypto-currency/repository.go
>  		ctx,
@ihippik исправил на обычный JOIN, просто когда писал запрос пробовал разные варианты)

2024-05-12 13:04 UTC, ihippik commented on cmd/api/main.go
>  func init() {
init словетую не использовать - не явное поведение

2024-05-12 13:04 UTC, ihippik commented on cmd/api/main.go
> +	defer logger.Info("Programm was shutdown")
логи лучше все писать с маленькой буквы - у тебя сейчас и так и так

2024-05-12 13:04 UTC, ihippik commented on cmd/api/main.go
> +
для двух строк смысла нет пустую строку делать - нужно линтер настроить соответсвующе

2024-05-12 13:04 UTC, ihippik commented on config/config.go
> +	UpdateTimeInMinutes   int      `env:"UPDATE_TIME_IN_MINUTES,required"`
продуктовый конфиг советую тоже вынести в отдельную структуру

2024-05-12 13:04 UTC, ihippik commented on internal/app/app.go
>  	httpServer *http.Server
для чего он тут? ты что его используешь из нескольких методов?

2024-05-12 13:04 UTC, ihippik commented on internal/app/app.go
>  	router := gin.Default()
используй стандартный - чем меньше зависимостей тем лучше

2024-05-12 13:04 UTC, ihippik commented on cmd/api/main.go
> +	db, err := app.InitDBConn(&cfg.DB)
почему инициализация на сервисом уровне?

2024-05-12 13:04 UTC, ihippik commented on internal/cryptocurr/handler.go
> +	service service
параметр можешь назвать svc  и короче и с интерфейсом различие

2024-05-12 13:04 UTC, ihippik commented on internal/cryptocurr/handler.go
> +
пустые строки не оставляют в кейсах

2024-05-12 13:04 UTC, ihippik commented on internal/cryptocurr/model.go
> +func NewDTO(model *CryptoCurrency, statsModel *Stats) *DTO {
нет коментария - у всего экпортируемого он должен быть

2024-05-12 13:04 UTC, ihippik commented on internal/cryptocurr/repository.go
> +WITH
напиши плиз на каждым запросмом в комменте что ты пытаешься сделать - подумаю как можно улучшить

2024-05-12 13:04 UTC, ihippik commented on internal/cryptocurr/service.go
> +		s.logger.Error("failed to get model by title: " + title + " :" + err.Error())
slog - структурный логер - если ты хочешь добавить какие-то параметры - доабвляй их как нвоыяе поля а не в текст сообщения

2024-05-12 13:04 UTC, ihippik commented on internal/cryptocurr/service.go
> +	go func() {
замем анонимная функция если ты этот метод можешь вызвать как рутину?

2024-06-18 11:53 UTC, merged